import { StyleSheet } from 'react-native';
import { COLORS, LAYOUT, RADII, SPACING } from '@/constants/theme';

export const styles = StyleSheet.create({
  content: {
    padding: SPACING.md,
    paddingBottom: LAYOUT.screenBottomPadding,
    gap: SPACING.sm,
  },
  backButton: {
    alignSelf: 'flex-start',
  },
  backText: {
    color: COLORS.textSecondary,
    fontWeight: '800',
  },
  hero: {
    padding: SPACING.sm + 4,
    borderRadius: RADII.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    overflow: 'hidden',
  },
  backPill: {
    padding: 8,
    borderRadius: 999,
    borderWidth: 1,
  },
  backPillStep2: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: 'rgba(239, 68, 68, 0.2)',
  },
  footerBackBtn: {
    minHeight: 52,
    minWidth: 110,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    paddingHorizontal: 18,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '800',
  },
  infoShort: {
    fontSize: 12,
    lineHeight: 18,
  },
  infoLine2: {
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  documentScanRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: RADII.md,
    borderWidth: 1,
  },
  documentScanRowText: {
    flex: 1,
    gap: 4,
  },
  documentScanRowTitle: {
    fontSize: 14,
    fontWeight: '800',
  },
  documentScanRowMeta: {
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 15,
  },
  documentScanIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  heroEyebrow: {
    color: COLORS.accent,
    fontWeight: '900',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
  },
  subtitle: {
    color: COLORS.textSecondary,
    lineHeight: 21,
  },
  modeRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  modeChip: {
    flex: 1,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: RADII.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceStrong,
  },
  modeChipActive: {
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(56,189,248,0.12)',
  },
  modeChipText: {
    fontWeight: '800',
  },
  stepIndicatorRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  stepIndicator: {
    flex: 1,
    borderRadius: RADII.lg,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    backgroundColor: COLORS.surfaceStrong,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  stepIndicatorActive: {
    borderColor: COLORS.accent,
    backgroundColor: 'rgba(249,115,22,0.14)',
  },
  stepIndicatorText: {
    fontWeight: '800',
    fontSize: 13,
  },
  card: {
    gap: SPACING.sm,
    padding: SPACING.md + 2,
    borderRadius: RADII.xl,
    backgroundColor: COLORS.surfaceStrong,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: COLORS.textSecondary,
  },
  fieldError: {
    color: COLORS.danger,
    fontSize: 12,
    fontWeight: '700',
    marginTop: -SPACING.xs + 2,
  },
  helperText: {
    fontSize: 11,
    color: COLORS.textMuted,
    lineHeight: 16,
  },
  input: {
    minHeight: 48,
    borderRadius: 16,
    paddingHorizontal: 16,
    backgroundColor: COLORS.surfaceStrong,
    borderWidth: 1,
    borderColor: 'rgba(128, 176, 255, 0.24)',
    color: COLORS.text,
  },
  textarea: {
    minHeight: 64,
    maxHeight: 100,
    textAlignVertical: 'top',
    paddingTop: 8,
    fontSize: 14,
  },
  pickerField: {
    minHeight: 48,
    borderRadius: 16,
    paddingHorizontal: 16,
    justifyContent: 'center',
    backgroundColor: COLORS.surfaceStrong,
    borderWidth: 1,
    borderColor: 'rgba(128, 176, 255, 0.24)',
  },
  pickerText: {
    color: COLORS.text,
    fontWeight: '700',
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: RADII.md,
    backgroundColor: COLORS.backgroundSecondary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  invoiceTypeBlock: { paddingBottom: 2 },
  invoiceHeaderRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginBottom: 8 },
  invoicePairRow: { flexDirection: 'row', gap: SPACING.sm },
  invoiceCheckPress: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 40,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: RADII.sm,
    borderWidth: 1,
  },
  invoiceCheckBox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentRow: {
    flexDirection: 'row',
    gap: SPACING.xs,
  },
  segmentButton: {
    flex: 1,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: RADII.sm,
    backgroundColor: COLORS.backgroundSecondary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  segmentButtonActive: {
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(56,189,248,0.12)',
  },
  segmentText: {
    fontWeight: '800',
  },
  selectableCard: {
    padding: SPACING.sm,
    borderRadius: RADII.lg,
    backgroundColor: COLORS.backgroundSecondary,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 4,
  },
  selectableCardActive: {
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(56,189,248,0.12)',
  },
  selectableTitle: {
    fontWeight: '800',
    fontSize: 15,
  },
  selectableMeta: {
    color: COLORS.textSecondary,
    fontSize: 13,
  },
  stockAdjustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: SPACING.xs,
    marginTop: SPACING.xs,
  },
  countActionButton: {
    width: 34,
    height: 34,
    borderRadius: RADII.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: 'rgba(128, 176, 255, 0.24)',
  },
  countActionButtonDisabled: {
    opacity: 0.45,
  },
  countActionText: {
    fontSize: 18,
    fontWeight: '900',
    color: COLORS.text,
  },
  countInput: {
    width: 56,
    height: 38,
    borderRadius: RADII.sm,
    textAlign: 'center',
    backgroundColor: COLORS.surfaceStrong,
    borderWidth: 1,
    borderColor: 'rgba(128, 176, 255, 0.24)',
    color: COLORS.text,
    fontWeight: '800',
  },
  selectedPill: {
    minWidth: 28,
    height: 28,
    paddingHorizontal: SPACING.xs,
    borderRadius: RADII.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
  },
  selectedPillText: {
    color: COLORS.background,
    fontWeight: '900',
    fontSize: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryTitle: {
    fontWeight: '900',
    fontSize: 16,
  },
  summaryMeta: {
    color: COLORS.textSecondary,
    fontWeight: '700',
  },
  lineCard: {
    gap: SPACING.xs,
    padding: SPACING.sm,
    borderRadius: RADII.lg,
    backgroundColor: COLORS.backgroundSecondary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  lineCardActive: {
    borderColor: COLORS.accent,
    backgroundColor: 'rgba(249,115,22,0.08)',
  },
  lineTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  lineIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  lineQtyInput: {
    minWidth: 48,
    maxWidth: 72,
    textAlign: 'right',
    fontSize: 16,
    fontWeight: '900',
    paddingVertical: 4,
  },
  lineAdet: {
    fontSize: 12,
    fontWeight: '700',
  },
  lineHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.xs,
  },
  lineTitle: {
    fontWeight: '800',
    fontSize: 15,
  },
  lineMeta: {
    color: COLORS.textSecondary,
    fontSize: 13,
  },
  expandButton: {
    width: 28,
    height: 28,
    borderRadius: RADII.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.card,
  },
  expandButtonText: {
    fontWeight: '900',
    fontSize: 16,
  },
  warehousePicker: {
    minHeight: 44,
    borderRadius: RADII.sm,
    justifyContent: 'center',
    paddingHorizontal: SPACING.sm,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  warehousePickerText: {
    fontWeight: '700',
  },
  detailGrid: {
    gap: SPACING.xs,
  },
  detailLabel: {
    color: COLORS.textSecondary,
    fontWeight: '700',
    fontSize: 12,
  },
  detailInput: {
    minHeight: 42,
    borderRadius: RADII.sm,
    paddingHorizontal: SPACING.sm,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    color: COLORS.text,
  },
  emptyState: {
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.xxl,
  },
  emptyStateTitle: {
    fontWeight: '900',
    fontSize: 16,
  },
  emptyStateText: {
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(5, 10, 22, 0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  successModal: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 28,
    padding: 24,
    gap: 14,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: '900',
  },
  successMessage: {
    color: COLORS.textSecondary,
    lineHeight: 22,
  },
  secondaryButton: {
    minHeight: 52,
    minWidth: 110,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceStrong,
    paddingHorizontal: 18,
  },
  secondaryButtonText: {
    fontWeight: '800',
  },
  infieldCard: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: RADII.md,
    borderWidth: 1,
    borderColor: 'rgba(15, 23, 42, 0.08)',
  },
  infieldSection: {
    marginTop: 2,
    paddingTop: 6,
    borderTopWidth: StyleSheet.hairlineWidth,
  },
  mainTabBar: {
    flexDirection: 'row',
    padding: 4,
    borderRadius: RADII.lg,
    gap: 4,
  },
  mainTab: {
    flex: 1,
    minHeight: 40,
    borderRadius: RADII.md,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  mainTabText: {
    fontSize: 13,
    fontWeight: '800',
  },
  subTabRow: {
    flexDirection: 'row',
    gap: SPACING.lg,
    marginBottom: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(15, 23, 42, 0.08)',
  },
  subTab: {
    flex: 1,
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    marginBottom: -1,
    alignItems: 'center',
  },
  subTabActive: {
    borderBottomColor: COLORS.primary,
  },
  subTabText: { fontSize: 14, fontWeight: '700' },
  heroInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm + 2,
  },
  heroIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  continueBtn: {
    minHeight: 50,
    borderRadius: 999,
    paddingHorizontal: 20,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  continueText: { color: '#fff', fontWeight: '800', fontSize: 15 },
  orderSearchBlock: {
    marginTop: SPACING.sm,
    marginBottom: 10,
  },
  orderSearchShell: {
    borderRadius: RADII.md,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 2,
    minHeight: 44,
    justifyContent: 'center',
  },
  orderSearchField: {
    fontSize: 14,
    fontWeight: '500',
    paddingVertical: 8,
    paddingHorizontal: 0,
    minHeight: 40,
  },
  orderListCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: SPACING.md,
    borderRadius: RADII.lg,
    gap: SPACING.sm,
    borderWidth: 1,
  },
  orderCheck: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderListTitle: { fontWeight: '800', fontSize: 16 },
  orderListMeta: { fontSize: 13, fontWeight: '500' },
});
