import { StyleSheet } from 'react-native';
import { COLORS, LAYOUT, RADII, SPACING } from '@/constants/theme';

export const styles = StyleSheet.create({
  content: {
    padding: SPACING.lg,
    paddingBottom: LAYOUT.screenBottomPadding,
    gap: SPACING.md,
  },
  backButton: {
    alignSelf: 'flex-start',
  },
  backText: {
    color: COLORS.textSecondary,
    fontWeight: '800',
  },
  hero: {
    gap: SPACING.xs,
    padding: SPACING.lg,
    borderRadius: RADII.xxl,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  heroEyebrow: {
    color: COLORS.accent,
    fontWeight: '900',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  title: {
    fontSize: 28,
    fontWeight: '900',
  },
  subtitle: {
    color: COLORS.textSecondary,
    lineHeight: 21,
  },
  modeRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  modeChip: {
    flex: 1,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: RADII.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceStrong,
  },
  modeChipActive: {
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(56,189,248,0.12)',
  },
  modeChipText: {
    fontWeight: '800',
  },
  stepIndicatorRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  stepIndicator: {
    flex: 1,
    borderRadius: RADII.lg,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.sm,
    backgroundColor: COLORS.surfaceStrong,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  stepIndicatorActive: {
    borderColor: COLORS.accent,
    backgroundColor: 'rgba(249,115,22,0.14)',
  },
  stepIndicatorText: {
    fontWeight: '800',
    fontSize: 13,
  },
  card: {
    gap: SPACING.sm,
    padding: SPACING.md + 2,
    borderRadius: RADII.xl,
    backgroundColor: COLORS.surfaceStrong,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  fieldLabel: {
    fontWeight: '800',
    color: COLORS.textSecondary,
  },
  fieldError: {
    color: COLORS.danger,
    fontSize: 12,
    fontWeight: '700',
    marginTop: -SPACING.xs + 2,
  },
  helperText: {
    color: COLORS.textMuted,
    lineHeight: 19,
  },
  input: {
    minHeight: 48,
    borderRadius: 16,
    paddingHorizontal: 16,
    backgroundColor: COLORS.surfaceStrong,
    borderWidth: 1,
    borderColor: 'rgba(128, 176, 255, 0.24)',
    color: COLORS.text,
  },
  textarea: {
    minHeight: 96,
    textAlignVertical: 'top',
    paddingTop: 14,
  },
  pickerField: {
    minHeight: 48,
    borderRadius: 16,
    paddingHorizontal: 16,
    justifyContent: 'center',
    backgroundColor: COLORS.surfaceStrong,
    borderWidth: 1,
    borderColor: 'rgba(128, 176, 255, 0.24)',
  },
  pickerText: {
    color: COLORS.text,
    fontWeight: '700',
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.md,
    borderRadius: RADII.lg,
    backgroundColor: COLORS.backgroundSecondary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: SPACING.xs,
  },
  segmentButton: {
    flex: 1,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: RADII.sm,
    backgroundColor: COLORS.backgroundSecondary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  segmentButtonActive: {
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(56,189,248,0.12)',
  },
  segmentText: {
    fontWeight: '800',
  },
  selectableCard: {
    padding: SPACING.sm,
    borderRadius: RADII.lg,
    backgroundColor: COLORS.backgroundSecondary,
    borderWidth: 1,
    borderColor: COLORS.border,
    gap: 4,
  },
  selectableCardActive: {
    borderColor: COLORS.primary,
    backgroundColor: 'rgba(56,189,248,0.12)',
  },
  selectableTitle: {
    fontWeight: '800',
    fontSize: 15,
  },
  selectableMeta: {
    color: COLORS.textSecondary,
    fontSize: 13,
  },
  stockAdjustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: SPACING.xs,
    marginTop: SPACING.xs,
  },
  countActionButton: {
    width: 34,
    height: 34,
    borderRadius: RADII.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: 'rgba(128, 176, 255, 0.24)',
  },
  countActionButtonDisabled: {
    opacity: 0.45,
  },
  countActionText: {
    fontSize: 18,
    fontWeight: '900',
    color: COLORS.text,
  },
  countInput: {
    width: 56,
    height: 38,
    borderRadius: RADII.sm,
    textAlign: 'center',
    backgroundColor: COLORS.surfaceStrong,
    borderWidth: 1,
    borderColor: 'rgba(128, 176, 255, 0.24)',
    color: COLORS.text,
    fontWeight: '800',
  },
  selectedPill: {
    minWidth: 28,
    height: 28,
    paddingHorizontal: SPACING.xs,
    borderRadius: RADII.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
  },
  selectedPillText: {
    color: COLORS.background,
    fontWeight: '900',
    fontSize: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryTitle: {
    fontWeight: '900',
    fontSize: 16,
  },
  summaryMeta: {
    color: COLORS.textSecondary,
    fontWeight: '700',
  },
  lineCard: {
    gap: SPACING.xs,
    padding: SPACING.sm,
    borderRadius: RADII.lg,
    backgroundColor: COLORS.backgroundSecondary,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  lineCardActive: {
    borderColor: COLORS.accent,
    backgroundColor: 'rgba(249,115,22,0.08)',
  },
  lineHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.xs,
  },
  lineTitle: {
    fontWeight: '800',
    fontSize: 15,
  },
  lineMeta: {
    color: COLORS.textSecondary,
    fontSize: 13,
  },
  expandButton: {
    width: 28,
    height: 28,
    borderRadius: RADII.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.card,
  },
  expandButtonText: {
    fontWeight: '900',
    fontSize: 16,
  },
  warehousePicker: {
    minHeight: 44,
    borderRadius: RADII.sm,
    justifyContent: 'center',
    paddingHorizontal: SPACING.sm,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  warehousePickerText: {
    fontWeight: '700',
  },
  detailGrid: {
    gap: SPACING.xs,
  },
  detailLabel: {
    color: COLORS.textSecondary,
    fontWeight: '700',
    fontSize: 12,
  },
  detailInput: {
    minHeight: 42,
    borderRadius: RADII.sm,
    paddingHorizontal: SPACING.sm,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    color: COLORS.text,
  },
  emptyState: {
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.xxl,
  },
  emptyStateTitle: {
    fontWeight: '900',
    fontSize: 16,
  },
  emptyStateText: {
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(5, 10, 22, 0.72)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  successModal: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 28,
    padding: 24,
    gap: 14,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: '900',
  },
  successMessage: {
    color: COLORS.textSecondary,
    lineHeight: 22,
  },
  secondaryButton: {
    minHeight: 52,
    minWidth: 110,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surfaceStrong,
    paddingHorizontal: 18,
  },
  secondaryButtonText: {
    fontWeight: '800',
  },
});
