import { COLORS } from '@/constants/theme';
import type { WorkflowModuleConfig, WorkflowModuleKey } from '../types/workflow';

const standardAssignedFilters = [
  { value: 'documentNo', type: 'text', labelKey: 'paged.columns.documentNo' },
  { value: 'customerCode', type: 'text', labelKey: 'paged.columns.customerCode' },
  { value: 'customerName', type: 'text', labelKey: 'paged.columns.customerName' },
  { value: 'sourceWarehouse', type: 'text', labelKey: 'paged.columns.sourceWarehouse' },
  { value: 'targetWarehouse', type: 'text', labelKey: 'paged.columns.targetWarehouse' },
  { value: 'documentType', type: 'text', labelKey: 'paged.columns.documentType' },
] as const;

const goodsReceiptAssignedFilters = [
  { value: 'orderId', type: 'text', labelKey: 'paged.columns.orderId' },
  { value: 'customerCode', type: 'text', labelKey: 'paged.columns.customerCode' },
  { value: 'projectCode', type: 'text', labelKey: 'paged.columns.projectCode' },
  { value: 'documentType', type: 'text', labelKey: 'paged.columns.documentType' },
] as const;

export const WORKFLOW_MODULES: readonly WorkflowModuleConfig[] = [
  {
    key: 'goods-receipt',
    titleKey: 'workflow.goodsReceipt.title',
    subtitleKey: 'workflow.goodsReceipt.subtitle',
    createTitleKey: 'workflow.goodsReceipt.createTitle',
    createDescriptionKey: 'workflow.goodsReceipt.createDescription',
    assignedTitleKey: 'workflow.goodsReceipt.assignedTitle',
    assignedDescriptionKey: 'workflow.goodsReceipt.assignedDescription',
    pendingTitleKey: 'workflow.goodsReceipt.pendingTitle',
    pendingTextKey: 'workflow.goodsReceipt.pendingText',
    emptyTitleKey: 'workflow.goodsReceipt.emptyTitle',
    emptyDescriptionKey: 'workflow.goodsReceipt.emptyDescription',
    loadFailedKey: 'workflow.goodsReceipt.loadFailed',
    defaultFilterColumn: 'orderId',
    filterColumns: goodsReceiptAssignedFilters,
    assignedEndpoint: '/api/GrHeader/assigned',
    listEndpoint: '/api/GrHeader',
    importLineEndpoint: '/api/GrImportLine',
    lineEndpoint: '/api/GrLine',
    lineSerialEndpoint: '/api/GrLineSerial',
    routeEndpoint: '/api/GrRoute',
    terminalLineEndpoint: '/api/GrTerminalLine',
    accent: COLORS.success,
    iconKey: 'receipt',
  },
  {
    key: 'transfer',
    titleKey: 'workflow.transfer.title',
    subtitleKey: 'workflow.transfer.subtitle',
    createTitleKey: 'workflow.transfer.createTitle',
    createDescriptionKey: 'workflow.transfer.createDescription',
    assignedTitleKey: 'workflow.transfer.assignedTitle',
    assignedDescriptionKey: 'workflow.transfer.assignedDescription',
    pendingTitleKey: 'workflow.transfer.pendingTitle',
    pendingTextKey: 'workflow.transfer.pendingText',
    emptyTitleKey: 'workflow.transfer.emptyTitle',
    emptyDescriptionKey: 'workflow.transfer.emptyDescription',
    loadFailedKey: 'workflow.transfer.loadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/WtHeader/assigned',
    listEndpoint: '/api/WtHeader',
    importLineEndpoint: '/api/WtImportLine',
    lineEndpoint: '/api/WtLine',
    lineSerialEndpoint: '/api/WtLineSerial',
    routeEndpoint: '/api/WtRoute',
    terminalLineEndpoint: '/api/WtTerminalLine',
    accent: COLORS.primary,
    iconKey: 'transfer',
  },
  {
    key: 'warehouse-inbound',
    titleKey: 'workflow.warehouseInbound.title',
    subtitleKey: 'workflow.warehouseInbound.subtitle',
    createTitleKey: 'workflow.warehouseInbound.createTitle',
    createDescriptionKey: 'workflow.warehouseInbound.createDescription',
    assignedTitleKey: 'workflow.warehouseInbound.assignedTitle',
    assignedDescriptionKey: 'workflow.warehouseInbound.assignedDescription',
    pendingTitleKey: 'workflow.warehouseInbound.pendingTitle',
    pendingTextKey: 'workflow.warehouseInbound.pendingText',
    emptyTitleKey: 'workflow.warehouseInbound.emptyTitle',
    emptyDescriptionKey: 'workflow.warehouseInbound.emptyDescription',
    loadFailedKey: 'workflow.warehouseInbound.loadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/WiHeader/assigned',
    listEndpoint: '/api/WiHeader',
    importLineEndpoint: '/api/WiImportLine',
    lineEndpoint: '/api/WiLine',
    lineSerialEndpoint: '/api/WiLineSerial',
    routeEndpoint: '/api/WiRoute',
    terminalLineEndpoint: '/api/WiTerminalLine',
    accent: '#22c55e',
    iconKey: 'inbound',
  },
  {
    key: 'warehouse-outbound',
    titleKey: 'workflow.warehouseOutbound.title',
    subtitleKey: 'workflow.warehouseOutbound.subtitle',
    createTitleKey: 'workflow.warehouseOutbound.createTitle',
    createDescriptionKey: 'workflow.warehouseOutbound.createDescription',
    assignedTitleKey: 'workflow.warehouseOutbound.assignedTitle',
    assignedDescriptionKey: 'workflow.warehouseOutbound.assignedDescription',
    pendingTitleKey: 'workflow.warehouseOutbound.pendingTitle',
    pendingTextKey: 'workflow.warehouseOutbound.pendingText',
    emptyTitleKey: 'workflow.warehouseOutbound.emptyTitle',
    emptyDescriptionKey: 'workflow.warehouseOutbound.emptyDescription',
    loadFailedKey: 'workflow.warehouseOutbound.loadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/WoHeader/assigned',
    listEndpoint: '/api/WoHeader',
    importLineEndpoint: '/api/WoImportLine',
    lineEndpoint: '/api/WoLine',
    lineSerialEndpoint: '/api/WoLineSerial',
    routeEndpoint: '/api/WoRoute',
    terminalLineEndpoint: '/api/WoTerminalLine',
    accent: COLORS.accent,
    iconKey: 'outbound',
  },
  {
    key: 'shipment',
    titleKey: 'workflow.shipment.title',
    subtitleKey: 'workflow.shipment.subtitle',
    createTitleKey: 'workflow.shipment.createTitle',
    createDescriptionKey: 'workflow.shipment.createDescription',
    assignedTitleKey: 'workflow.shipment.assignedTitle',
    assignedDescriptionKey: 'workflow.shipment.assignedDescription',
    pendingTitleKey: 'workflow.shipment.pendingTitle',
    pendingTextKey: 'workflow.shipment.pendingText',
    emptyTitleKey: 'workflow.shipment.emptyTitle',
    emptyDescriptionKey: 'workflow.shipment.emptyDescription',
    loadFailedKey: 'workflow.shipment.loadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/ShHeader/assigned',
    listEndpoint: '/api/ShHeader',
    importLineEndpoint: '/api/ShImportLine',
    lineEndpoint: '/api/ShLine',
    lineSerialEndpoint: '/api/ShLineSerial',
    routeEndpoint: '/api/ShRoute',
    terminalLineEndpoint: '/api/ShTerminalLine',
    accent: '#8b5cf6',
    iconKey: 'shipment',
  },
  {
    key: 'subcontracting-issue',
    titleKey: 'workflow.subcontractingIssue.title',
    subtitleKey: 'workflow.subcontractingIssue.subtitle',
    createTitleKey: 'workflow.subcontractingIssue.createTitle',
    createDescriptionKey: 'workflow.subcontractingIssue.createDescription',
    assignedTitleKey: 'workflow.subcontractingIssue.assignedTitle',
    assignedDescriptionKey: 'workflow.subcontractingIssue.assignedDescription',
    pendingTitleKey: 'workflow.subcontractingIssue.pendingTitle',
    pendingTextKey: 'workflow.subcontractingIssue.pendingText',
    emptyTitleKey: 'workflow.subcontractingIssue.emptyTitle',
    emptyDescriptionKey: 'workflow.subcontractingIssue.emptyDescription',
    loadFailedKey: 'workflow.subcontractingIssue.loadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/SitHeader/assigned',
    listEndpoint: '/api/SitHeader',
    importLineEndpoint: '/api/SitImportLine',
    lineEndpoint: '/api/SitLine',
    lineSerialEndpoint: '/api/SitLineSerial',
    routeEndpoint: '/api/SitRoute',
    terminalLineEndpoint: '/api/SitTerminalLine',
    accent: '#ec4899',
    iconKey: 'issue',
  },
  {
    key: 'subcontracting-receipt',
    titleKey: 'workflow.subcontractingReceipt.title',
    subtitleKey: 'workflow.subcontractingReceipt.subtitle',
    createTitleKey: 'workflow.subcontractingReceipt.createTitle',
    createDescriptionKey: 'workflow.subcontractingReceipt.createDescription',
    assignedTitleKey: 'workflow.subcontractingReceipt.assignedTitle',
    assignedDescriptionKey: 'workflow.subcontractingReceipt.assignedDescription',
    pendingTitleKey: 'workflow.subcontractingReceipt.pendingTitle',
    pendingTextKey: 'workflow.subcontractingReceipt.pendingText',
    emptyTitleKey: 'workflow.subcontractingReceipt.emptyTitle',
    emptyDescriptionKey: 'workflow.subcontractingReceipt.emptyDescription',
    loadFailedKey: 'workflow.subcontractingReceipt.loadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/SrtHeader/assigned',
    listEndpoint: '/api/SrtHeader',
    importLineEndpoint: '/api/SrtImportLine',
    lineEndpoint: '/api/SrtLine',
    lineSerialEndpoint: '/api/SrtLineSerial',
    routeEndpoint: '/api/SrtRoute',
    terminalLineEndpoint: '/api/SrtTerminalLine',
    accent: '#14b8a6',
    iconKey: 'receiptSub',
  },
] as const;

export function getWorkflowModule(key: string | undefined): WorkflowModuleConfig | undefined {
  return WORKFLOW_MODULES.find((module) => module.key === key);
}

export function isWorkflowModuleKey(value: string): value is WorkflowModuleKey {
  return WORKFLOW_MODULES.some((module) => module.key === value);
}
