import { COLORS } from '@/constants/theme';
import type { WorkflowModuleConfig, WorkflowModuleKey } from '../types/workflow';

const standardAssignedFilters = [
  { value: 'documentNo', type: 'text', labelKey: 'paged.columns.documentNo' },
  { value: 'customerCode', type: 'text', labelKey: 'paged.columns.customerCode' },
  { value: 'customerName', type: 'text', labelKey: 'paged.columns.customerName' },
  { value: 'sourceWarehouse', type: 'text', labelKey: 'paged.columns.sourceWarehouse' },
  { value: 'targetWarehouse', type: 'text', labelKey: 'paged.columns.targetWarehouse' },
  { value: 'documentType', type: 'text', labelKey: 'paged.columns.documentType' },
] as const;

const goodsReceiptAssignedFilters = [
  { value: 'orderId', type: 'text', labelKey: 'paged.columns.orderId' },
  { value: 'customerCode', type: 'text', labelKey: 'paged.columns.customerCode' },
  { value: 'projectCode', type: 'text', labelKey: 'paged.columns.projectCode' },
  { value: 'documentType', type: 'text', labelKey: 'paged.columns.documentType' },
] as const;

export const WORKFLOW_MODULES: readonly WorkflowModuleConfig[] = [
  {
    key: 'goods-receipt',
    viewPermissionCode: 'wms.goods-receipt.view',
    createPermissionCode: 'wms.goods-receipt.create',
    updatePermissionCode: 'wms.goods-receipt.update',
    titleKey: 'workflow.goodsReceipt.title',
    subtitleKey: 'workflow.goodsReceipt.subtitle',
    createTitleKey: 'workflow.goodsReceipt.createTitle',
    createDescriptionKey: 'workflow.goodsReceipt.createDescription',
    createInfoLine2Key: 'workflow.goodsReceipt.createInfoLine2',
    assignedTitleKey: 'workflow.goodsReceipt.assignedTitle',
    assignedDescriptionKey: 'workflow.goodsReceipt.assignedDescription',
    approvalTitleKey: 'workflow.goodsReceipt.approvalTitle',
    approvalDescriptionKey: 'workflow.goodsReceipt.approvalDescription',
    pendingTitleKey: 'workflow.goodsReceipt.pendingTitle',
    pendingTextKey: 'workflow.goodsReceipt.pendingText',
    approvalPendingTitleKey: 'workflow.goodsReceipt.approvalPendingTitle',
    approvalPendingTextKey: 'workflow.goodsReceipt.approvalPendingText',
    emptyTitleKey: 'workflow.goodsReceipt.emptyTitle',
    emptyDescriptionKey: 'workflow.goodsReceipt.emptyDescription',
    approvalEmptyTitleKey: 'workflow.goodsReceipt.approvalEmptyTitle',
    approvalEmptyDescriptionKey: 'workflow.goodsReceipt.approvalEmptyDescription',
    loadFailedKey: 'workflow.goodsReceipt.loadFailed',
    approvalLoadFailedKey: 'workflow.goodsReceipt.approvalLoadFailed',
    defaultFilterColumn: 'orderId',
    filterColumns: goodsReceiptAssignedFilters,
    assignedEndpoint: '/api/GrHeader/assigned',
    listEndpoint: '/api/GrHeader',
    approvalListEndpoint: '/api/GrHeader/completed-awaiting-erp-approval',
    approvalActionEndpoint: '/api/GrHeader/approval',
    importLineEndpoint: '/api/GrImportLine',
    lineEndpoint: '/api/GrLine',
    lineSerialEndpoint: '/api/GrLineSerial',
    routeEndpoint: '/api/GrRoute',
    terminalLineEndpoint: '/api/GrTerminalLine',
    accent: COLORS.success,
    iconKey: 'receipt',
  },
  {
    key: 'transfer',
    viewPermissionCode: 'wms.transfer.view',
    createPermissionCode: 'wms.transfer.create',
    updatePermissionCode: 'wms.transfer.update',
    titleKey: 'workflow.transfer.title',
    subtitleKey: 'workflow.transfer.subtitle',
    createTitleKey: 'workflow.transfer.createTitle',
    createDescriptionKey: 'workflow.transfer.createDescription',
    createInfoLine2Key: 'workflow.transfer.createInfoLine2',
    assignedTitleKey: 'workflow.transfer.assignedTitle',
    assignedDescriptionKey: 'workflow.transfer.assignedDescription',
    approvalTitleKey: 'workflow.transfer.approvalTitle',
    approvalDescriptionKey: 'workflow.transfer.approvalDescription',
    pendingTitleKey: 'workflow.transfer.pendingTitle',
    pendingTextKey: 'workflow.transfer.pendingText',
    approvalPendingTitleKey: 'workflow.transfer.approvalPendingTitle',
    approvalPendingTextKey: 'workflow.transfer.approvalPendingText',
    emptyTitleKey: 'workflow.transfer.emptyTitle',
    emptyDescriptionKey: 'workflow.transfer.emptyDescription',
    approvalEmptyTitleKey: 'workflow.transfer.approvalEmptyTitle',
    approvalEmptyDescriptionKey: 'workflow.transfer.approvalEmptyDescription',
    loadFailedKey: 'workflow.transfer.loadFailed',
    approvalLoadFailedKey: 'workflow.transfer.approvalLoadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/WtHeader/assigned',
    listEndpoint: '/api/WtHeader',
    approvalListEndpoint: '/api/WtHeader/completed-awaiting-erp-approval',
    approvalActionEndpoint: '/api/WtHeader/approval',
    importLineEndpoint: '/api/WtImportLine',
    lineEndpoint: '/api/WtLine',
    lineSerialEndpoint: '/api/WtLineSerial',
    routeEndpoint: '/api/WtRoute',
    terminalLineEndpoint: '/api/WtTerminalLine',
    accent: COLORS.primary,
    iconKey: 'transfer',
  },
  {
    key: 'warehouse-inbound',
    viewPermissionCode: 'wms.warehouse.inbound.view',
    createPermissionCode: 'wms.warehouse.inbound.create',
    updatePermissionCode: 'wms.warehouse.inbound.update',
    titleKey: 'workflow.warehouseInbound.title',
    subtitleKey: 'workflow.warehouseInbound.subtitle',
    createTitleKey: 'workflow.warehouseInbound.createTitle',
    createDescriptionKey: 'workflow.warehouseInbound.createDescription',
    createInfoLine2Key: 'workflow.warehouseInbound.createInfoLine2',
    assignedTitleKey: 'workflow.warehouseInbound.assignedTitle',
    assignedDescriptionKey: 'workflow.warehouseInbound.assignedDescription',
    approvalTitleKey: 'workflow.warehouseInbound.approvalTitle',
    approvalDescriptionKey: 'workflow.warehouseInbound.approvalDescription',
    pendingTitleKey: 'workflow.warehouseInbound.pendingTitle',
    pendingTextKey: 'workflow.warehouseInbound.pendingText',
    approvalPendingTitleKey: 'workflow.warehouseInbound.approvalPendingTitle',
    approvalPendingTextKey: 'workflow.warehouseInbound.approvalPendingText',
    emptyTitleKey: 'workflow.warehouseInbound.emptyTitle',
    emptyDescriptionKey: 'workflow.warehouseInbound.emptyDescription',
    approvalEmptyTitleKey: 'workflow.warehouseInbound.approvalEmptyTitle',
    approvalEmptyDescriptionKey: 'workflow.warehouseInbound.approvalEmptyDescription',
    loadFailedKey: 'workflow.warehouseInbound.loadFailed',
    approvalLoadFailedKey: 'workflow.warehouseInbound.approvalLoadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/WiHeader/assigned',
    listEndpoint: '/api/WiHeader',
    approvalListEndpoint: '/api/WiHeader/completed-awaiting-erp-approval',
    approvalActionEndpoint: '/api/WiHeader/approval',
    importLineEndpoint: '/api/WiImportLine',
    lineEndpoint: '/api/WiLine',
    lineSerialEndpoint: '/api/WiLineSerial',
    routeEndpoint: '/api/WiRoute',
    terminalLineEndpoint: '/api/WiTerminalLine',
    accent: '#22c55e',
    iconKey: 'inbound',
  },
  {
    key: 'warehouse-outbound',
    viewPermissionCode: 'wms.warehouse.outbound.view',
    createPermissionCode: 'wms.warehouse.outbound.create',
    updatePermissionCode: 'wms.warehouse.outbound.update',
    titleKey: 'workflow.warehouseOutbound.title',
    subtitleKey: 'workflow.warehouseOutbound.subtitle',
    createTitleKey: 'workflow.warehouseOutbound.createTitle',
    createDescriptionKey: 'workflow.warehouseOutbound.createDescription',
    createInfoLine2Key: 'workflow.warehouseOutbound.createInfoLine2',
    assignedTitleKey: 'workflow.warehouseOutbound.assignedTitle',
    assignedDescriptionKey: 'workflow.warehouseOutbound.assignedDescription',
    approvalTitleKey: 'workflow.warehouseOutbound.approvalTitle',
    approvalDescriptionKey: 'workflow.warehouseOutbound.approvalDescription',
    pendingTitleKey: 'workflow.warehouseOutbound.pendingTitle',
    pendingTextKey: 'workflow.warehouseOutbound.pendingText',
    approvalPendingTitleKey: 'workflow.warehouseOutbound.approvalPendingTitle',
    approvalPendingTextKey: 'workflow.warehouseOutbound.approvalPendingText',
    emptyTitleKey: 'workflow.warehouseOutbound.emptyTitle',
    emptyDescriptionKey: 'workflow.warehouseOutbound.emptyDescription',
    approvalEmptyTitleKey: 'workflow.warehouseOutbound.approvalEmptyTitle',
    approvalEmptyDescriptionKey: 'workflow.warehouseOutbound.approvalEmptyDescription',
    loadFailedKey: 'workflow.warehouseOutbound.loadFailed',
    approvalLoadFailedKey: 'workflow.warehouseOutbound.approvalLoadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/WoHeader/assigned',
    listEndpoint: '/api/WoHeader',
    approvalListEndpoint: '/api/WoHeader/completed-awaiting-erp-approval',
    approvalActionEndpoint: '/api/WoHeader/approval',
    importLineEndpoint: '/api/WoImportLine',
    lineEndpoint: '/api/WoLine',
    lineSerialEndpoint: '/api/WoLineSerial',
    routeEndpoint: '/api/WoRoute',
    terminalLineEndpoint: '/api/WoTerminalLine',
    accent: COLORS.accent,
    iconKey: 'outbound',
  },
  {
    key: 'shipment',
    viewPermissionCode: 'wms.shipment.view',
    createPermissionCode: 'wms.shipment.create',
    updatePermissionCode: 'wms.shipment.update',
    titleKey: 'workflow.shipment.title',
    subtitleKey: 'workflow.shipment.subtitle',
    createTitleKey: 'workflow.shipment.createTitle',
    createDescriptionKey: 'workflow.shipment.createDescription',
    createInfoLine2Key: 'workflow.shipment.createInfoLine2',
    assignedTitleKey: 'workflow.shipment.assignedTitle',
    assignedDescriptionKey: 'workflow.shipment.assignedDescription',
    approvalTitleKey: 'workflow.shipment.approvalTitle',
    approvalDescriptionKey: 'workflow.shipment.approvalDescription',
    pendingTitleKey: 'workflow.shipment.pendingTitle',
    pendingTextKey: 'workflow.shipment.pendingText',
    approvalPendingTitleKey: 'workflow.shipment.approvalPendingTitle',
    approvalPendingTextKey: 'workflow.shipment.approvalPendingText',
    emptyTitleKey: 'workflow.shipment.emptyTitle',
    emptyDescriptionKey: 'workflow.shipment.emptyDescription',
    approvalEmptyTitleKey: 'workflow.shipment.approvalEmptyTitle',
    approvalEmptyDescriptionKey: 'workflow.shipment.approvalEmptyDescription',
    loadFailedKey: 'workflow.shipment.loadFailed',
    approvalLoadFailedKey: 'workflow.shipment.approvalLoadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/ShHeader/assigned',
    listEndpoint: '/api/ShHeader',
    approvalListEndpoint: '/api/ShHeader/completed-awaiting-erp-approval',
    approvalActionEndpoint: '/api/ShHeader/approval',
    importLineEndpoint: '/api/ShImportLine',
    lineEndpoint: '/api/ShLine',
    lineSerialEndpoint: '/api/ShLineSerial',
    routeEndpoint: '/api/ShRoute',
    terminalLineEndpoint: '/api/ShTerminalLine',
    accent: '#8b5cf6',
    iconKey: 'shipment',
  },
  {
    key: 'subcontracting-issue',
    viewPermissionCode: 'wms.subcontracting.issue.view',
    createPermissionCode: 'wms.subcontracting.issue.create',
    updatePermissionCode: 'wms.subcontracting.issue.update',
    titleKey: 'workflow.subcontractingIssue.title',
    subtitleKey: 'workflow.subcontractingIssue.subtitle',
    createTitleKey: 'workflow.subcontractingIssue.createTitle',
    createDescriptionKey: 'workflow.subcontractingIssue.createDescription',
    createInfoLine2Key: 'workflow.subcontractingIssue.createInfoLine2',
    assignedTitleKey: 'workflow.subcontractingIssue.assignedTitle',
    assignedDescriptionKey: 'workflow.subcontractingIssue.assignedDescription',
    approvalTitleKey: 'workflow.subcontractingIssue.approvalTitle',
    approvalDescriptionKey: 'workflow.subcontractingIssue.approvalDescription',
    pendingTitleKey: 'workflow.subcontractingIssue.pendingTitle',
    pendingTextKey: 'workflow.subcontractingIssue.pendingText',
    approvalPendingTitleKey: 'workflow.subcontractingIssue.approvalPendingTitle',
    approvalPendingTextKey: 'workflow.subcontractingIssue.approvalPendingText',
    emptyTitleKey: 'workflow.subcontractingIssue.emptyTitle',
    emptyDescriptionKey: 'workflow.subcontractingIssue.emptyDescription',
    approvalEmptyTitleKey: 'workflow.subcontractingIssue.approvalEmptyTitle',
    approvalEmptyDescriptionKey: 'workflow.subcontractingIssue.approvalEmptyDescription',
    loadFailedKey: 'workflow.subcontractingIssue.loadFailed',
    approvalLoadFailedKey: 'workflow.subcontractingIssue.approvalLoadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/SitHeader/assigned',
    listEndpoint: '/api/SitHeader',
    approvalListEndpoint: '/api/SitHeader/completed-awaiting-erp-approval',
    approvalActionEndpoint: '/api/SitHeader/approval',
    importLineEndpoint: '/api/SitImportLine',
    lineEndpoint: '/api/SitLine',
    lineSerialEndpoint: '/api/SitLineSerial',
    routeEndpoint: '/api/SitRoute',
    terminalLineEndpoint: '/api/SitTerminalLine',
    accent: '#ec4899',
    iconKey: 'issue',
  },
  {
    key: 'subcontracting-receipt',
    viewPermissionCode: 'wms.subcontracting.receipt.view',
    createPermissionCode: 'wms.subcontracting.receipt.create',
    updatePermissionCode: 'wms.subcontracting.receipt.update',
    titleKey: 'workflow.subcontractingReceipt.title',
    subtitleKey: 'workflow.subcontractingReceipt.subtitle',
    createTitleKey: 'workflow.subcontractingReceipt.createTitle',
    createDescriptionKey: 'workflow.subcontractingReceipt.createDescription',
    createInfoLine2Key: 'workflow.subcontractingReceipt.createInfoLine2',
    assignedTitleKey: 'workflow.subcontractingReceipt.assignedTitle',
    assignedDescriptionKey: 'workflow.subcontractingReceipt.assignedDescription',
    approvalTitleKey: 'workflow.subcontractingReceipt.approvalTitle',
    approvalDescriptionKey: 'workflow.subcontractingReceipt.approvalDescription',
    pendingTitleKey: 'workflow.subcontractingReceipt.pendingTitle',
    pendingTextKey: 'workflow.subcontractingReceipt.pendingText',
    approvalPendingTitleKey: 'workflow.subcontractingReceipt.approvalPendingTitle',
    approvalPendingTextKey: 'workflow.subcontractingReceipt.approvalPendingText',
    emptyTitleKey: 'workflow.subcontractingReceipt.emptyTitle',
    emptyDescriptionKey: 'workflow.subcontractingReceipt.emptyDescription',
    approvalEmptyTitleKey: 'workflow.subcontractingReceipt.approvalEmptyTitle',
    approvalEmptyDescriptionKey: 'workflow.subcontractingReceipt.approvalEmptyDescription',
    loadFailedKey: 'workflow.subcontractingReceipt.loadFailed',
    approvalLoadFailedKey: 'workflow.subcontractingReceipt.approvalLoadFailed',
    defaultFilterColumn: 'documentNo',
    filterColumns: standardAssignedFilters,
    assignedEndpoint: '/api/SrtHeader/assigned',
    listEndpoint: '/api/SrtHeader',
    approvalListEndpoint: '/api/SrtHeader/completed-awaiting-erp-approval',
    approvalActionEndpoint: '/api/SrtHeader/approval',
    importLineEndpoint: '/api/SrtImportLine',
    lineEndpoint: '/api/SrtLine',
    lineSerialEndpoint: '/api/SrtLineSerial',
    routeEndpoint: '/api/SrtRoute',
    terminalLineEndpoint: '/api/SrtTerminalLine',
    accent: '#14b8a6',
    iconKey: 'receiptSub',
  },
] as const;

export function getWorkflowModule(key: string | undefined): WorkflowModuleConfig | undefined {
  return WORKFLOW_MODULES.find((module) => module.key === key);
}

export function isWorkflowModuleKey(value: string): value is WorkflowModuleKey {
  return WORKFLOW_MODULES.some((module) => module.key === value);
}
